# Generated by Django 4.2.7 on 2026-05-02 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CivicIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_description', models.TextField(help_text='Description of the civic issue')),
                ('location', models.CharField(blank=True, help_text='Location of the issue', max_length=500)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, help_text='Latitude coordinate', max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, help_text='Longitude coordinate', max_digits=9, null=True)),
                ('category', models.CharField(help_text='Issue category (Sanitation, Road Infrastructure, etc.)', max_length=100)),
                ('severity', models.CharField(help_text='Severity level (low, medium, high, critical)', max_length=20)),
                ('urgency', models.CharField(help_text='Urgency level (low, medium, high, immediate)', max_length=20)),
                ('reasoning', models.TextField(help_text='AI reasoning for classification')),
                ('formatted_complaint', models.TextField(help_text='AI-generated formal complaint')),
                ('authority_department', models.CharField(help_text='Responsible department', max_length=200)),
                ('authority_jurisdiction', models.CharField(help_text='Jurisdiction area', max_length=200)),
                ('authority_contact', models.CharField(help_text='Contact person/office', max_length=200)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('rejected', 'Rejected')], default='pending', help_text='Current status of the issue', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the issue was reported')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last update time')),
                ('view_count', models.IntegerField(default=0, help_text='Number of times this issue was viewed')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='api_civicis_created_092074_idx'), models.Index(fields=['category'], name='api_civicis_categor_2fa6c0_idx'), models.Index(fields=['severity'], name='api_civicis_severit_762236_idx'), models.Index(fields=['status'], name='api_civicis_status_70053a_idx')],
            },
        ),
    ]
