# Generated by Django 4.2.7 on 2026-05-02 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='civicissue',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='Latitude coordinate', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='civicissue',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='Longitude coordinate', max_digits=12, null=True),
        ),
    ]
