# Generated by Django 4.2.7 on 2026-05-02 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_civicissue_latitude_alter_civicissue_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='civicissue',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=20, help_text='Latitude coordinate', max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='civicissue',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=20, help_text='Longitude coordinate', max_digits=20, null=True),
        ),
    ]
