# Generated by Django 4.2.7 on 2026-05-02 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_civicissue_latitude_alter_civicissue_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='civicissue',
            name='latitude',
            field=models.FloatField(blank=True, help_text='Latitude coordinate (optional)', null=True),
        ),
        migrations.AlterField(
            model_name='civicissue',
            name='longitude',
            field=models.FloatField(blank=True, help_text='Longitude coordinate (optional)', null=True),
        ),
    ]
