# Generated by Django 4.2.7 on 2026-05-02 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_civicissue_latitude_alter_civicissue_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='civicissue',
            name='escalated_at',
            field=models.DateTimeField(blank=True, help_text='When issue was escalated', null=True),
        ),
        migrations.AddField(
            model_name='civicissue',
            name='escalation_level',
            field=models.CharField(choices=[('ward', 'Ward'), ('city', 'City'), ('emergency', 'Emergency')], default='ward', help_text='Current escalation level', max_length=20),
        ),
        migrations.AddField(
            model_name='civicissue',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='Whether issue is verified as legitimate'),
        ),
        migrations.AddField(
            model_name='civicissue',
            name='verification_score',
            field=models.IntegerField(default=0, help_text='Trust score 0-100 based on multiple factors'),
        ),
        migrations.AddField(
            model_name='civicissue',
            name='vote_count',
            field=models.IntegerField(default=0, help_text='Number of upvotes from community'),
        ),
    ]
